### ISSUE TITLE
Add package.properties

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/MarkdownEditor#7]
### Feature proposal

See https://vaadin.com/docs/latest/flow/integrations/spring/configuration#jar-packages-scanning

**Comment by javier-godoy** [comment]
Based on `https://github.com/vaadin/docs/issues/3929` I think it's pointless to add `package.properties`.
(IIRC we agreed to keep them in other add-ons since it's harmless.)

**Comment by mlopezFC** [comment]
Closing because it is pointless to add that property at this point.
