### ISSUE TITLE
Resize Height inside FormLayout

### ISSUE THREAD

**Issue by FernandoLomazzi** [FlowingCode/MarkdownEditor#8]
### Feature proposal

If the component is added as an item in a form layout, it cannot change its height. To do so, you need to insert the component within a layout, which is impractical and generates repetitive code.

**Comment by mlopezFC** [comment]
I tested this briefly and it works as expected (if you set a given height it uses it), see screenshot:
![image](https://github.com/user-attachments/assets/a8b0d7c2-0a5f-4b22-88e6-53ce2334c49f)
So I'm closing this ticket for now.
